---

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

ADD ROLE INFO

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

ADD ROLE INFO

- name: deploy postgres
  hosts: apps
  gather_facts: false
  become: true
  hosts: appdbs

