  - name: install postgresql
    package:
      name: postgresql-server
      state: latest

  - name: enable postgresql at boot
    service:
      name: postgresql
      enabled: yes

  - name: initilize postgres
    command: postgresql-setup initdb

  - name: start postgres
    service:
      name: postgresql.service
      state: restarted
