---
# tasks file for apps
#
  - name: install tomcat on app nodes
    package:
      name: tomcat
      state: latest

  - name: enable tomcat at boot
    service:
      name: tomcat
      enabled: yes

  - name: create tomcat directory
    file:
      path: "{{ tomcat_root }}"
      state: directory

  - name: copy static index.html to {{ tomcat_root }}
    template:
      src: index.html.j2
      dest: "{{ tomcat_root }}/index.html"
      mode: 0644

  - name: start tomcat
    service:
      name: tomcat
      state: restarted


