---
# tasks file for frontend
#

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: Install Frontend Software
    package:
      name: haproxy
      state: latest
  - name: enable HAProxy
    service:
      name: haproxy
      enabled: yes
  - name: configure haproxy
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: Start Haproxy
    service:
      name: haproxy
      state: restarted
