---
# tasks file for frontend
#

- name: Install Frontend Software
  package:
    name: haproxy
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Start Haproxy
  service:
    name: haproxy
    state: restarted
